@startuml
'https://plantuml.com/component-diagram

node "Client (via HTTP)"{
    () request
    () response
}


node "Backend Infrastructure 1"{

    package "Node-js" {

        package "Express-js" {
            frame "control flow orchestrator"{
                [Server]
            }

            frame "middleware 1"{
                [JSON parser]
                [LoggerMiddleware]


                [ValidationMiddleware]
            }


            frame "routes"{
                [AccountRoute]
                [AuthRoute]
                [CartRoute]
                [OrderRoute]
                [ProductRoute]
            }

            [AuthMiddleware]

            frame "middleware 2"{
                node "ErrorMiddleware"{
                }
            }
        }
    }
}

node "Business Logic"{

    frame "controllers"{
        [AccountController]
        [AuthController]
        [CartController]
        [ProductController]
        [CheckoutController]
    }

    frame "services"{
        [AccountService]
        [AuthService]
        [CartService]
        [ProductService]
        [CheckoutService]
    }

    frame "models"{
        [AccountModel]
        [CartModel]
        [ProductModel]
        [OrderModel]
    }
}

node "Backend Infrastructure 2"{
    [Mongoose]

    frame "repositories"{
        [AccountRepository]
        [CartRepository]
        [ProductRepository]
        [UserRepository]
    }

    database "MongoDB" {
    }

}

request -down-> [Server]
[Server] -right-> response

[Server] -down-> [JSON parser]
[JSON parser] -down-> [LoggerMiddleware]
[LoggerMiddleware] -down-> [ValidationMiddleware]

"middleware 1" --> [ErrorMiddleware]
"routes" -down-> [ErrorMiddleware]
[ErrorMiddleware] <-up-> [Server]

[ValidationMiddleware] <..> "models" : Schema based validation (type, format, constraints)
[ValidationMiddleware] -down-> "routes"

[AuthMiddleware] <--> [AuthRoute]
[AuthRoute] <--> [AuthController]
[AuthController] <--> [AuthService]

[AccountRoute] -down-> [AccountController]
[CartRoute] -down-> [CartController]
[OrderRoute] -down-> [CheckoutController]
[ProductRoute] -down-> [ProductController]

[AccountController] <--> [AccountService]
[CartController] <--> [CartService]
[ProductController] <--> [ProductService]
[CheckoutController] <--> [CheckoutService]
"controllers" -right-> [Server]


"services" <..> "models" : First getting data schemes

"services" <-down-> [Mongoose] : Then heading to DB
[Mongoose] <-down-> "repositories" : Conversing with backend persistence layer
"repositories" <-down-> "MongoDB"























@enduml